all : bitonic_sequential quicksort_sequential

bitonic_sequential: bitonic_sequential.cpp
	g++ -std=c++11 -o bitonic_sequential bitonic_sequential.cpp

quicksort_sequential: quicksort_sequential.cpp
	g++ -std=c++11 -o quicksort_sequential quicksort_sequential.cpp

